export const environment = {
  production: true,
  name: 'Queries Care',
  domain: 'queriescare.com',
  apiBaseLink: 'https://api.queriescare.com',
  ftpBaseLink: 'https://api.queriescare.com',
  appBaseUrl: '/',
  // userBaseUrl: '/',
  userBaseUrl: 'account',
  newUserBaseUrl: 'update-profile',
  userProfileUrl: '/my-profile',
  userLoginUrl: '/login',
  adminLoginUrl: 'login',
  adminBaseUrl: '/',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  VERSION: 1
};
